I want to go to ANTARTICA!!!!!!!
UCL-COMP0233-24-25/Travel-guide pull request #17
Opened 2024-10-07 10:30 UTC by Songzx07

@AngelosZou

Answers UCL-COMP0233-24-25/RSE-Classwork#3

2024-10-07 10:36 UTC, azure80 approved these changes
Nice stufff

2024-10-11 16:27 UTC, dpshelio requested changes
:antarctica: Very nice an cool! Please, fix the small suggestion on Antartica's readme.

2024-10-11 16:27 UTC, dpshelio commented on antarctica/README.md
> +# Look
The title of this file should be called Antartica

2024-10-11 16:37 UTC, dpshelio approved these changes
Yay! :tada:

2024-10-11 16:38 UTC, merged

2024-10-11 16:45 UTC, Songzx07 commented
Cheers to the ultimate travel guid! Hooray!