Add Norway/Oslo
UCL-COMP0233-24-25/Travel-guide pull request #19
Opened 2024-10-07 10:32 UTC by shiyingwucl

Answers UCL-COMP0233-24-25/RSE-Classwork#3

2024-10-11 16:29 UTC, dpshelio requested changes
Alsmot there. There are a couple of suggestions you need to update to get this approved.
One more thing, the title of the PR is not meaningful, update that accordingly.

2024-10-11 16:29 UTC, dpshelio commented on README.md
> +- [Norway/Oslo](./europe/norway/oslo.md)
This can't stay in the top readme file, it needs to have one inside Europa's `README.md` and then create one more for Norway that points to Oslo.

2024-10-11 16:29 UTC, dpshelio commented on europe/norway/oslo.md
> +Oslo
This should be a title in markdown.

2024-10-11 16:43 UTC, dpshelio requested changes
Still some small fixes to do.

2024-10-11 16:43 UTC, dpshelio commented on README.md
> +     - [Oslo](./europe/norway/oslo.md)
Those needs to be in different files, checkout how they are the approved PRs.

2024-10-11 17:54 UTC, dpshelio requested changes
Almost there! there's a small typo the automated checker has picked up.

2024-10-11 17:54 UTC, dpshelio commented on europe/norway/README.md
> +[Oslo](./oslo.md)
This page needs a title!!

2024-10-11 18:12 UTC, shiyingwucl commented on europe/norway/README.md
> +[Oslo](./oslo.md)
Oops!

2024-10-11 18:21 UTC, shiyingwucl reviewed
Add title in norway/readme.md

2024-10-18 16:39 UTC, dpshelio approved these changes
:tada:

2024-10-18 16:39 UTC, merged