Victor B Pull request
UCL-COMP0233-24-25/Travel-guide pull request #21
Opened 2024-10-07 10:35 UTC by VictorBay24

Adding Vietnam-Hanoi to the travel giude

2024-10-07 10:36 UTC, PyrgosRuairi commented
You didnt link the issue!

2024-10-11 16:46 UTC, dpshelio requested changes
Almost perfect. You need to update a link, and then I'll suggest updating the title of the PR with something more meaningful (eg. "Hanoi") and add the issue this PR refers to on the body of the PR as instructed.

2024-10-11 16:46 UTC, dpshelio commented on asia/README.md
> +[Vietnam](./Vietnam)
This needs to link to the `README.md` file, no the folder.

2024-10-18 16:41 UTC, dpshelio approved these changes
:tada:

2024-10-18 16:41 UTC, merged