Ruairi's Travel Recommendation
UCL-COMP0233-24-25/Travel-guide pull request #7
Opened 2024-10-07 10:27 UTC by PyrgosRuairi

https://github.com/UCL-COMP0233-24-25/RSE-Classwork/issues/3

2024-10-07 10:31 UTC, r4b61t approved these changes
Looks good. Approved

2024-10-11 16:07 UTC, dpshelio requested changes
Thanks for your contribution. Fix the link that's making the checker to fail so it can be merged.

2024-10-11 16:07 UTC, dpshelio commented on europe/README.md
> +[Cyprus](./cyprus/)
Link needs to point to the readme file, not the folder.

2024-10-18 16:45 UTC, dpshelio approved these changes
:tada:

2024-10-18 16:46 UTC, merged